apiVersion: v1
kind: Service
metadata:
  name: order-processor-svc
spec:
  type: NodePort
  selector:
    app: order-processor
    version: v1.1
  ports:
    - port: 8000
      targetPort: 8000
      nodePort: 30080
