apiVersion: apps/v1
kind: Deployment
metadata:
  name: front-desk
  labels:
    app: guestbook
    tier: frontend
spec:
  replicas: 3
  selector:
    matchLabels:
      app: guestbook
      tier: frontend
  template:
    metadata:
      labels:
        app: guestbook
        tier: frontend
    spec:
      containers:
        - name: front-desk
          image: nginx:1.25
          ports:
            - containerPort: 80
