apiVersion: v1
kind: Pod
metadata:
  name: front-desk
  labels:
    app: guestbook
    tier: frontend
spec:
  containers:
    - name: front-desk
      image: nginx:1.25
      ports:
        - containerPort: 80
