apiVersion: v1
kind: Pod
metadata:
  name: order-processor-pod
spec:
  containers:
    - name: order-processor
      image: rithvikreddyalkanti/order-processor:v1.0
      ports:
        - containerPort: 8000
      resources:
        requests:
          cpu: "100m"
          memory: "128Mi"
